
        <img src="http://www.institut-de-france.fr/sites/institut-de-france.fr/files/styles/diaporama/public/institut_900_320.jpg?itok=MAo-_W0J" id="imgevent" alt="image évènement"/>
    <section id="taille">
        <h1 id="titre"><?php echo($model[2]); ?></h1>
        <section class="infoinitial">
            <div class="debutfin">
                <p>
                    Début : xx/xx/xxxx
                </p>
                <p>
                    Fin : xx/xx/xxxx
                </p>
            </div>
            <div class="statut">
                <p>
                    Statut : En Cours
                </p>
                <div class="bouton">
                <a href="n'existepas.com" class="topicforum">
                    Topic forum
                </a>
                </div>
            </div>
            <div class="placesprix">
                <p>
                    Nombre de places : xxxx
                </p>
                <p>
                    Prix : xxxx
                </p>
            </div>
        </section>
        <section>
            <div class="description">
                <h1>Description</h1>
                <p>
                    Dès la troisième édition de son dictionnaire (1740), l'Académie française indique l'orthographe événement. Lors de la septième édition (1878), l'Académie a rectifié l'accentuation de plusieurs mots pour suivre l'évolution phonétique de la langue : ainsi, collége et avénement ont été changés en collège et avènement. Toutefois, quelques mots, dont événement, n'ont pas été rectifiés, et cette orthographe est toujours utilisée au XXIe siècle1.
Le Rapport de 1990 sur les rectifications orthographiques préconise la régularisation de tels mots2, et les dictionnaires, dès la fin du XXe siècle, encouragent l'orthographe évènement, quoique l'autre orthographe soit aussi mentionnée3,4,5. Toutefois ce rapport n'a jamais été entériné dans sa globalité par l'Académie française, bien au contraire. Celle-ci accepte toutefois la graphie évènement, mais estime que « la graphie ancienne événement n'est cependant pas considérée comme fautive, encore que rien ne la justifie plus »1. Les recommandations orthographiques, dont fait partie évènement, sont plus enseignées et connues dans d'autres pays francophones comme la Suisse ou la Belgique qu'en France, puisqu'elles n'ont jamais reçu de caractère officiel6.
                </p>
            </div>
        </section>
            <div>
                <img src="<?php echo Config::get('config.base'); ?>/apps/events/images/petite_salle_institut.jpg" alt="diapo de photo" class="image"/>
            </div>
        <div class="adresse">
                <h2>
                    Adresse
                </h2>
                <p>
               18 rue blablaba Paris 75015
                </p>
            </div>
            <div class="text1">
                <ul>
               <li> <h2>Organisateur   </h2>
                <p class="organisateur">
                     Mr.A
                   </p></li>
               <li><h2>Téléphone   </h2>
                <p class="telephone">
                    0612345678
                   </p></li>
                <li><h2>Entreprise   </h2>
                <p class="entreprise">
                         blabla
                    </p></li>
                </ul>
                <div id="blanc">
                <ul>
                <li><h2>Site</h2>
                <p class="site">
                        xxxxxxxxx
                    </p></li>
                <li><h2>Partenaire</h2>
                <p class="partenaire">
                        xxxxxxxxxxxxx
                    </p></li>
                </ul>
                </div>
            </div>
            <ul id="boutons">
                <li><div class="bouton">
                <a href="INCONNU.wtf" class="bouton">
                    S'incrire
                </a>
            </div>
            </li>
            <li><div class="bouton">
                <a href="TJRPAS.com">
                    Ajouter aux favoris
                </a>
            </div>
                </li>
                <li>
                <div class="bouton">
                <a href="...." >
                    Contacter par mail
                </a>
            </div>
                </li>
            </ul>
            <div>
                <p class="note">
                    Note moyenne :
                </p>
                <div class="bouton">
                <a href="rhnzearazer" class="badge">
                    Demander le badge
                </a>
                </div>
            </div>
        <section id="fin">
            <div class="article">
                <h1>
                    Article
                </h1>
                <p>
                    SKF (Svenska KullagerFabriken, littéralement: "Fabrique suédoise de roulements à billes") est un groupe multinational suédois, leader mondial dans le domaine du roulement mécanique. Son siège social se trouve à Göteborg1.

    Présent dans près de 70 pays, SKF emploie près de 43 000 personnes à travers le monde, pour un chiffre d'affaires de 61 milliards de couronnes suédoises en 2010 (soit 6,7 milliards d'euros).
                </p>
            </div>
            <div class="bouton" id="lire">
            <a href="zaerhzaeurhn">Lire plus  </a>
            </div>
            <div style="clear:both;"></div>
        </section>
        </section>
    </body>
</html>
